# Generated by Django 6.0.3 on 2026-04-03 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Telefono', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'fabricante',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Cantidad', models.SmallIntegerField()),
                ('ValorCompra', models.IntegerField()),
                ('ValorVenta', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('Fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.fabricante')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
            options={
                'db_table': 'subcategoria',
            },
        ),
        migrations.CreateModel(
            name='ProductosCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
                ('Subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.subcategoria')),
            ],
            options={
                'db_table': 'productoscategoria',
                'unique_together': {('Productos', 'Subcategoria')},
            },
        ),
    ]
