# Generated by Django 6.0.3 on 2026-04-03 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEncargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.IntegerField()),
                ('Fecha', models.DateTimeField()),
                ('Usuario', models.ForeignKey(db_column='Usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registroencargo',
            },
        ),
        migrations.CreateModel(
            name='CantidadEncargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.SmallIntegerField()),
                ('Productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
                ('RegistroEncargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CantidadEncargo', to='compras.registroencargo')),
            ],
            options={
                'db_table': 'cantidadencargo',
            },
        ),
    ]
