# Generated by Django 5.2.1 on 2025-09-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriomarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cantidadventa',
            old_name='ValorUnitario',
            new_name='ValorVentaUnitario',
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
