# Generated by Django 5.2.1 on 2025-09-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriomarket', '0002_rename_valorunitario_cantidadventa_valorventaunitario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroventa',
            old_name='id',
            new_name='idRegistroVenta',
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='DocumentoCliente',
            field=models.CharField(max_length=12),
        ),
    ]
