# Generated by Django 5.2.1 on 2025-09-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriomarket', '0003_rename_id_registroventa_idregistroventa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroventa',
            name='idRegistroVenta',
        ),
        migrations.AddField(
            model_name='registroventa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='DocumentoCliente',
            field=models.BigIntegerField(),
        ),
    ]
