# Generated by Django 5.2.1 on 2025-09-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriomarket', '0004_remove_registroventa_idregistroventa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantidadventa',
            name='ValorVentaUnitario',
        ),
    ]
