# Generated by Django 5.2.1 on 2025-09-29 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriomarket', '0005_remove_cantidadventa_valorventaunitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantidadventa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registroventa',
            name='id',
        ),
        migrations.AddField(
            model_name='cantidadventa',
            name='id_cantidadventa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='registroventa',
            name='id_ventas',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_cancelacion', models.DateTimeField(auto_now_add=True)),
                ('valor', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='barriomarket.registropedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devoluciones',
            },
        ),
    ]
