# Generated by Django 6.0.3 on 2026-04-03 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Documento', models.CharField(max_length=12, unique=True)),
                ('Primer_nombre', models.CharField(max_length=30)),
                ('Primer_apellido', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=15)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
