# Generated by Django 6.0.3 on 2026-04-03 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=45)),
                ('Contador', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'registrofalta',
            },
        ),
        migrations.CreateModel(
            name='UsuarioProductoFaltante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentoCliente', models.BigIntegerField()),
                ('Fecha', models.DateTimeField()),
                ('IdProductoFaltante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faltantes.registrofalta')),
            ],
            options={
                'db_table': 'usuarioproductofaltante',
            },
        ),
    ]
