# Generated by Django 6.0.3 on 2026-04-03 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposMetodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tiposmetodo',
            },
        ),
        migrations.CreateModel(
            name='RegistroVenta',
            fields=[
                ('id_ventas', models.AutoField(primary_key=True, serialize=False)),
                ('Valor', models.IntegerField()),
                ('ValorTotal', models.IntegerField()),
                ('Fecha', models.DateTimeField()),
                ('DocumentoCliente', models.BigIntegerField()),
                ('Usuario_DocumentoAdministrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registroventa',
            },
        ),
        migrations.CreateModel(
            name='CantidadVenta',
            fields=[
                ('id_cantidadventa', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('Productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
                ('RegistroVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.registroventa')),
            ],
            options={
                'db_table': 'cantidadventa',
            },
        ),
        migrations.CreateModel(
            name='MetodosVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegistroVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.registroventa')),
                ('TiposMetodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.tiposmetodo')),
            ],
            options={
                'db_table': 'metodosventa',
            },
        ),
    ]
